---
name: Deploy
run-name: "Deploy to ${{ inputs.env || 'dev' }} (${{ github.head_ref || github.ref_name }})"

on:
  push:
    branches:
      - development    # Triggers when a PR is merged to the development branch
  workflow_call:
    inputs:
      env:
        description: 'Environment (dev or prd)'
        required: false
        type: string
        default: dev
  workflow_dispatch:
    inputs:
      env:
        description: 'Environment'
        required: false
        type: choice
        default: dev
        options:
          - dev
          - prd

jobs:
  # 🚀 Deploy job
  deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_ENV: ${{ inputs.env || 'dev' }}
    steps:
      - uses: actions/checkout@v7
      - run: npm install -g @shopify/cli @shopify/theme

      - name: Setup uv
        uses: astral-sh/setup-uv@v8.3.2
        with:
          enable-cache: true

      - name: Install Dependencies
        run: uv sync

      - name: Deploy to ${{ env.DEPLOY_ENV }} Theme
        run: |
          uv run --no-sync invoke debug.env
          uv run --no-sync invoke shopify.deploy --env=${{ env.DEPLOY_ENV }}
        env:
          SHOPIFY_CLI_THEME_TOKEN: ${{ secrets.SHOPIFY_CLI_THEME_TOKEN }}
          SHOPIFY_FLAG_STORE: ${{ secrets.SHOPIFY_FLAG_STORE }}
          SHOPIFY_THEME_ID_DEV: ${{ secrets.SHOPIFY_THEME_ID_DEV }}
          SHOPIFY_THEME_ID_PRD: ${{ secrets.SHOPIFY_THEME_ID_PRD }}
