---
name: Merge
run-name: "Merge (${{ github.head_ref || github.ref_name }})"

on:
  push:
    branches:
      - development    # Triggers when a PR is merged to the development branch

jobs:
  deploy:
    uses: ./.github/workflows/deploy.yml
    with:
      env: dev
    secrets: inherit
